run:
  timeout: 3m
go: '1.18'
linters:
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - ifshort
    - importas
    - ineffassign
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilnil
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - staticcheck
    - tenv
    - thelper
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace