openapi: 3.0.1
info:
  title: Parcel Tracking
  description: REST API
  version: 1.0.0
tags:
  - name: Tracker
    description: ""
paths:
  /tracking:
    get:
      tags:
        - "Tracker"
      summary: "Find parcel"
      parameters:
        - in: query
          name: "tracking_id"
          description: "Id of parcel"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Parcels'
        "400":
          description: "Invalid ID supplied"
components:
  schemas:
    Parcels:
      type: object
      properties:
        status:
          description: "Status"
          type: "string"
        track_id:
          description: "Track id"
          type: "string"
        address:
          description: "Delivery address"
          type: "string"