name: Test
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Test Race
        run: go test -v ./... -race

      - name: Test Cover
        run: go test ./... -cover

      - name: Fuzz Test
        run: cd ./pkg/determine-delivery/  &&  go test --fuzz=Fuzz -fuzztime=10s
